/*
 * ephemerkey lock board — 12 V solenoid driver (ATtiny1616)
 * See solenoid.h for the peak-and-hold rationale.
 *
 * Hold PWM is generated by TCD0 on WOB (= PA5, a fixed mux — TCD0 has no
 * PORTMUX alternate). ~31 kHz, above the audible band, so the coil/caps don't
 * whine (4 kHz software PWM did). 50 % duty is symmetric, so we don't depend on
 * the exact WOB on/off-region convention of one-ramp mode. TCD runs CPU-free,
 * so the LED heartbeat and (later) I2C are undisturbed during the hold.
 *
 * TCD0 quirks handled here: FAULTCTRL (output-enable) is CCP-protected and only
 * writable while disabled; CTRLA.ENABLE may only be written when STATUS.ENRDY
 * is set. We keep TCD disabled (PA5 = GPIO) for the DC strike/drain phases and
 * only enable it for the hold.
 */

#include <avr/io.h>
#include <avr/cpufunc.h>          /* _PROTECTED_WRITE */
#include <util/delay.h>
#include "solenoid.h"

#define SOL_PWM_bm      PIN5_bm    /* PORTA: PA5 = TCD0 WOB (Q1 gate) */

/* TCD0 clocked from the internal 20 MHz osc: 20e6 / (639+1) = 31.25 kHz. */
#define SOL_TCD_TOP     639u       /* CMPBCLR: period (TOP) */
#define SOL_TCD_HALF    320u       /* CMPBSET: ~50 % duty   */

void sol_init(void)
{
    PORTA.OUTCLR = SOL_PWM_bm;     /* GPIO output, low (Q1 off) */
    PORTA.DIRSET = SOL_PWM_bm;

    /* Pre-configure TCD0 for a fixed 50 %/31 kHz waveform on WOB. Leave the
     * timer DISABLED and the output override OFF, so PA5 stays a GPIO until the
     * hold phase enables it. */
    TCD0.CTRLB   = TCD_WGMODE_ONERAMP_gc;
    TCD0.CMPASET = 0;              /* WOA unused (PA4 = HALL_PWR) */
    TCD0.CMPACLR = 0;
    TCD0.CMPBSET = SOL_TCD_HALF;
    TCD0.CMPBCLR = SOL_TCD_TOP;
}

void sol_on(void)  { PORTA.OUTSET = SOL_PWM_bm; }   /* DC (TCD disabled) */
void sol_off(void) { PORTA.OUTCLR = SOL_PWM_bm; }

static void sol_pwm_on(void)
{
    _PROTECTED_WRITE(TCD0.FAULTCTRL, TCD_CMPBEN_bm);   /* connect WOB -> PA5 */
    while (!(TCD0.STATUS & TCD_ENRDY_bm)) { }
    TCD0.CTRLA = TCD_CLKSEL_20MHZ_gc | TCD_CNTPRES_DIV1_gc | TCD_ENABLE_bm;
}

static void sol_pwm_off(void)
{
    while (!(TCD0.STATUS & TCD_ENRDY_bm)) { }
    TCD0.CTRLA = TCD_CLKSEL_20MHZ_gc | TCD_CNTPRES_DIV1_gc;   /* disable */
    _PROTECTED_WRITE(TCD0.FAULTCTRL, 0);               /* release PA5 -> GPIO */
    PORTA.OUTSET = SOL_PWM_bm;                          /* GPIO high for drain */
}

void sol_peak_and_hold(uint16_t strike_ms, uint16_t hold_ms)
{
    /* --- strike: full DC drive to pull the armature in --- */
    sol_on();
    for (uint16_t i = 0; i < strike_ms; i++) _delay_ms(1);

    /* --- hold: hardware 31 kHz / 50 % PWM economizer (inaudible) --- */
    sol_pwm_on();
    for (uint16_t i = 0; i < hold_ms; i++) _delay_ms(1);
    sol_pwm_off();

    /* Leaves Q1 conducting (GPIO high) so the caller can drain VSOL. */
}
